version: 2.1

orbs:
  python: circleci/python@0.2.1
  
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          command: |
            chmod +x ./test.py
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          command: |   
            . venv/bin/activate
            pip install -r requirements.txt      
      - run:
          command: |
            . venv/bin/activate
            python test.py test

workflows:
  main:
    jobs:
      - build-and-test
